.TH CLOVER 1
.SH NAME
clover script language

clover
[-c command] [script file] --version
.PP

.SH DESCRIPTION
clover is a script language. You can run "clover" without any arguments to use it as an interactive shell.

The following options are available
.PP
--version
.br
output version
.PP
\-c " string"
.br
Commands described by string are executed and exit immediately.
.PP

.SH USAGE

.SH EXAMPLES
.PP

.SH COPYRIGHT
Copyright 2013 by ab25cq

